const ListOfHobbies = [
  {
    title: "Sports and Fitness",
    hobbies: [
      "Fitness",
      "Hiking",
      "Backpacking",
      "Biking",
      "Rock Climbing",
      "Camping",
      "Kayaking",
      "CrossFit",
      "Yoga",
      "Parkour",
      "Zumba",
      "Martial Arts",
      "Weightlifting",
      "Surfing",
      "Rowing",
      "Sailing",
      "Fishing",
      "Skateboarding",
      "Water Polo",
      "Tennis",
      "Gymnastics",
      "Basketball",
      "Soccer",
      "Football",
      "Volleyball",
      "Swimming",
      "Snowboarding",
      "Baseball",
      "Fencing",
    ],
  },
  {
    title: "Technology and Gaming",
    hobbies: [
      "Board Games",
      "Puzzles",
      "Coding",
      "Streaming",
      "Esports",
      "PC Building",
      "Graphic Design",
      "Animation",
      "Digital Art",
      "AI",
      "Video Editing",
      "Tech Gadgets",
      "Mobile Gaming",
      "3D Printing",
      "Chess",
      "Drone Flying",
      "Retro Gaming",
      "Web Design",
      "Electronics",
    ],
  },
  {
    title: "Nature and Science",
    hobbies: [
      "Bird Watching",
      "Astronomy",
      "Botany",
      "Gardening",
      "Zoology",
      "Marine Biology",
      "Earth Sciences",
      "Biology",
      "Chemistry",
      "Physics",
      "Engineering",
      "Psychology",
      "Archaeology",
      "BushCraft",
      "Science News",
      "DIY Science",
    ],
  },
  {
    title: "Music and Performance",
    hobbies: [
      "Theater",
      "Acting",
      "Playing Music",
      "Making Music",
      "Improv",
      "Dancing",
      "Singing",
      "Standup",
      "Magic",
      "DJing",
      "Acting",
      "Karaoke",
      "Beatboxing",
      "Rock",
      "Reggae",
      "Metal",
      "Funk",
      "Pop",
      "Latin Music",
      "Hip-hop",
      "Jazz",
      "Blues",
      "Country",
      "Techno",
      "House",
      "Trance Music",
      "Drum and Bass",
      "Bass Music",
      "Dubstep",
      "Hardcore",
      "Ambient",
      "Synthwave",
      "Lo-fi",
      "Electronica",
      "Disco",
      "Classical",
      "Indie",
      "Folk",
      "R&B",
    ],
  },
  {
    title: "Crafting Hobbies",
    hobbies: [
      "Pottery",
      "DIY Home Decor",
      "Painting",
      "Sewing",
      "Knitting",
      "Candle Making",
      "Scrapbooking",
      "Beading",
      "Calligraphy",
      "Origami",
      "Sculpting",
      "Woodworking",
      "Printmaking",
      "Embroidery",
      "Crocheting",
    ],
  },
  {
    title: "Collecting Hobbies",
    hobbies: [
      "Geocaching",
      "Vinyl",
      "Vintage Clothing",
      "Rare Coins",
      "Stamps",
      "Comic Books",
      "Manga",
      "Sneakers",
      "Retro Games",
      "Sportabilia",
      "Watches",
      "Classic Cars",
      "Trading Cards",
      "Fountain Pens",
    ],
  },
  {
    title: "Culinary Hobbies",
    hobbies: [
      "Cooking",
      "Baking",
      "Mixology",
      "Wine Connoisseur",
      "Beer Connoisseur",
      "Home Brewing",
      "BBQ",
      "Healthy Cooking",
      "Vegan",
      "Vegan Cooking",
      "International Cuisine",
      "Culinary Arts",
      "Nutritional Science",
    ],
  },
  {
    title: "General Hobbies",
    hobbies: [
      "Photography",
      "Movies",
      "Travel",
      "Reading",
      "Book Club",
      "Poetry",
      "Karaoke",
      "Volunteering",
      "Writing",
      "Reading",
      "Board Games",
      "Astrology",
      "Podcasts",
      "Meditation",
      "Learning",
      "Anime",
      "Politics",
      "Public Speaking",
      "Escape Room",
      "Fashion",
      "Meditation",
      "Cars",
      "Language",
    ],
  },
];

export default ListOfHobbies;
